default: &default
  adapter: postgresql
  encoding: unicode
  pool: 400

development:
  <<: *default
  database: homework_development

test:
  <<: *default
  database: homework_test

production:
  <<: *default
  database: homework_production
  username: homework
  password: <%= ENV['HOMEWORK_DATABASE_PASSWORD'] %>
